[qt]
GUIEffects=none
KDE\contrast=4
KWinPalette\activeBackground=#eff0f1
KWinPalette\activeBlend=#fcfcfc
KWinPalette\activeForeground=#0a0b0c
KWinPalette\activeTitleBtnBg=#eff0f1
KWinPalette\frame=#eff0f1
KWinPalette\inactiveBackground=#eff0f1
KWinPalette\inactiveBlend=#dddedf
KWinPalette\inactiveForeground=#696d6f
KWinPalette\inactiveFrame=#eff0f1
KWinPalette\inactiveTitleBtnBg=#eff0f1
Palette\active=#0a0b0c, #eff0f1, #ffffff, #f6f7f7, #888e93, #c4c8cc, #0a0b0c, #ffffff, #0a0b0c, #fcfcfc, #eff0f1, #474a4c, #3daee9, #0a0b0c, #2980b9, #7f8c8d, #eff0f1, #000000, #eff0f1, #0a0b0c, #7f8c8d, #3daee9
Palette\disabled=#979899, #e3e5e7, #ffffff, #ebedee, #82878c, #bbc0c5, #9fa0a0, #ffffff, #979899, #f0f0f0, #e3e5e7, #474a4c, #e3e5e7, #979899, #a2c8e0, #c7cbcb, #e3e5e7, #000000, #eff0f1, #0a0b0c, #c7cbcb, #e3e5e7
Palette\inactive=#0a0b0c, #eff0f1, #ffffff, #f6f7f7, #888e93, #c4c8cc, #0a0b0c, #ffffff, #0a0b0c, #fcfcfc, #eff0f1, #474a4c, #c2e0f5, #0a0b0c, #2980b9, #7f8c8d, #eff0f1, #000000, #eff0f1, #0a0b0c, #7f8c8d, #c2e0f5
font="Noto Sans,10,-1,0,400,0,0,0,0,0,0,0,0,0,0,1"
